### ISSUE TITLE
SetWhitelist throws a NullReferenceException

### ISSUE THREAD

**Issue by molinch** [halkar/Tesseract.Xamarin#12]
First all thanks for your amazing work... It's really impressive what you did.
With latest version from Nuget SetWhitelist throws a NullReferenceException.

Code sample:
<pre>
TesseractApi api = new TesseractApi();
api.SetWhitelist("ACDFMN123456789");
</pre>

**Comment by molinch** [comment]
Don't worry I looked in the code and saw that Init() should be performed before calling other methods :)

**Comment by halkar** [comment]
This is an issue actually. I should give more information about API actual state.
