### ISSUE TITLE
I'm using the sample code and it hangs

### ISSUE THREAD

**Issue by DiegoGLagash** [halkar/Tesseract.Xamarin#14]
When the SetImage method is called the operation never ends. The proress is not being updated. Is there an what is maximumRecognitionTime default? Do you know what might be happening?

**Comment by halkar** [comment]
I believe progress doesn't work in the current version. I'm sorry, please don't use it.

**Comment by halkar** [comment]
Apart from the progress does the application hangs? If yes, on which platform? Device/emulator?

**Comment by DiegoGLagash** [comment]
iOS 8.4, on emulator. Is there any log/trace i can use to capture?

**Comment by halkar** [comment]
Can you give me a sample you are working with?
