### ISSUE TITLE
Pre Processing Photo

### ISSUE THREAD

**Issue by marioaleogolsat** [halkar/Tesseract.Xamarin#18]
Hello,

I would like to know if there's any way to pre process the photo, by applying a grayscale filter and adjusting contrast, brightness, clip, saturation and other things like this.

Thanks.

**Comment by halkar** [comment]
There is no preprocessing in this library. It's only about OCR process itself.

**Comment by marioaleogolsat** [comment]
Is there any library for Xamarin.Forms that can play along with this OCR?
Or that can get the photo from XLabs, process it, and than pass it to the oCR?

Thanks for the help.

**Comment by halkar** [comment]
Yes, you can use OpenCV but I can't recommend any particular implementation for Xamarin.
