### ISSUE TITLE
How about WinPhone?

### ISSUE THREAD

**Issue by dazinator** [halkar/Tesseract.Xamarin#2]
To complete the trio?

**Comment by halkar** [comment]
I wasn't able to find how to build Tesseract for Windows Phone. And there is good OCR lib from Microsoft https://www.nuget.org/packages/Microsoft.Windows.Ocr/
So if you know how to build Tesseract for WP I can include it.

**Comment by dazinator** [comment]
Nah - no idea how to build it for windows phone! It's not that important really, so I'll close this - feel free to re-open if you really want to!
