### ISSUE TITLE
Could not find Tesseract.iOS

### ISSUE THREAD

**Issue by joaodealmeida** [halkar/Tesseract.Xamarin#24]
Hello, i've installed your Nuget Package in my solution. I could now find Tesseract.iOS so I can register the type TesseractAPI( which it doesn't recognise) in the container builder.
![screen shot 2015-12-22 at 17 13 45](https://cloud.githubusercontent.com/assets/5623455/11961275/6fededbe-a8cf-11e5-8570-f04dc7f46c28.png)

**Comment by halkar** [comment]
Which package version do you use?
Which version of Xamarin Studio?

**Comment by joaodealmeida** [comment]
Xamarin Studio: 5.10.1 (build 6)
Package : 0.2.12

**Comment by halkar** [comment]
Weird. So you created new cross-platform Xamarin.Forms app, right? Installed a nuget package and iOS dll is not added? Can you take a screenshot of your project references?
<img width="273" alt="screen shot 2015-12-23 at 12 39 00" src="https://cloud.githubusercontent.com/assets/1992396/11969734/2e7fe50a-a972-11e5-9556-ff38734dfaa9.png">

**Comment by joaodealmeida** [comment]
It didn't add any Tesseract iOs related.

![screen shot 2015-12-23 at 02 01 22](https://cloud.githubusercontent.com/assets/5623455/11969889/2cc51bbc-a919-11e5-9122-30087cf4e817.png)

**Comment by joaodealmeida** [comment]
Although in Android project I've got the Tesseract.Droid and Tesseract.Binding.Droid ...

**Comment by halkar** [comment]
I see the problem now. Your iOS app is classic and not universal one. Why do you use it? Tesseract.Xamarin only supports universal iOS apps.

Sent from Outlook Mobile




On Tue, Dec 22, 2015 at 6:09 PM -0800, "João Almeida" <notifications@github.com> wrote:












Although in Android project I've got the Tesseract.Droid and Tesseract.Binding.Droid ...

**Comment by joaodealmeida** [comment]
I've just updated to unified API. Now its properly loading the references!

Thanks
