### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by APistole** [halkar/Tesseract.Xamarin#26]
Even using your test projects, only garbage is returned.  Not only that, it takes well over 5 minutes, at least, to process an image. Only when taking an image directly from the camera or an image that was taken from the camera and loaded from the library. However, images downloaded from the web are read in just fine. Would this be a problem with the camera?

**Comment by halkar** [comment]
Can you share the image?

**Comment by halkar** [comment]
It's almost impossible to recognise image received from phone camera without preprocessing (like contrast, b/w, noise removing etc). Image preprocessing is not this lib's job so you will need to use something like OpenCV.
