### ISSUE TITLE
Tesseract.Droid.TesseractApi.Init hangs

### ISSUE THREAD

**Issue by pandrija** [halkar/Tesseract.Xamarin#27]
Started from Xamarin default Android app template, just added the tessdata files for English and called Init method, but execution hangs on Init method....

```fsharp
public class MainActivity : Activity
	{
		int count = 1;

		Tesseract.Droid.TesseractApi ocrApi;

		protected override void OnCreate (Bundle savedInstanceState)
		{
			base.OnCreate (savedInstanceState);

			this.ocrApi = new Tesseract.Droid.TesseractApi(this,
				Tesseract.Droid.AssetsDeployment.OncePerVersion);

			// Set our view from the "main" layout resource
			SetContentView (Resource.Layout.Main);

			// Get our button from the layout resource,
			// and attach an event to it
			Button button = FindViewById<Button> (Resource.Id.myButton);
			
			button.Click += delegate {
				button.Text = string.Format ("{0} clicks!", count++);
			};

			var result = this.ocrApi.Init("eng").Result;
		}
	}
}
```

![image](https://cloud.githubusercontent.com/assets/643004/14590007/4775c096-04f0-11e6-9a57-6a6bb8b50eec.png)

Here's the debugger output (last part):
[TesseractApi] Copy assets to /storage/emulated/0/Android/data/com.companyname.labelscanner/files
Thread started: <Thread Pool> #2
Thread started: <Thread Pool> #3
[Mono] [0x7f58a19450] worker starting
Thread started: <Thread Pool> #4
[Mono] [0x7f58814450] worker starting
[Mono] DllImport attempting to load: '/system/lib64/libc.so'.
[Mono] DllImport loaded library '/system/lib64/libc.so'.
[Mono] DllImport searching in: '/system/lib64/libc.so' ('/system/lib64/libc.so').
[Mono] Searching for 'gettid'.
[Mono] Probing 'gettid'.
[Mono] Found as 'gettid'.
Thread started: <Thread Pool> #5
[Mono] [0x7f585fc450] worker starting
[Mono] [0x7f58a19450] hill climbing, change max number of threads 8
[Mono] [0x7f58a19450] worker finishing
Thread finished: <Thread Pool> #3
Thread finished: <Thread Pool> #2
[Mono] [0x7f58814450] worker finishing
Thread finished: <Thread Pool> #4
Thread finished: <Thread Pool> #5
[Mono] [0x7f585fc450] worker finishing

**Comment by halkar** [comment]
@pandrija thanks, will have a look.

**Comment by halkar** [comment]
@pandrija do you use real device or emulator? Which version of Android do you use?

**Comment by halkar** [comment]
Don't use .Result. Instead use async/await
`using Android.App;
using Android.Widget;
using Android.OS;

namespace tesseract.test
{
    [Activity (Label = "tesseract.test", MainLauncher = true, Icon = "@mipmap/icon")]
    public class MainActivity : Activity
    {
        int count = 1;
        Tesseract.Droid.TesseractApi ocrApi;

        protected override async void OnCreate (Bundle savedInstanceState)
        {
            base.OnCreate (savedInstanceState);

            this.ocrApi = new Tesseract.Droid.TesseractApi (this,
                Tesseract.Droid.AssetsDeployment.OncePerInitialization);

            // Set our view from the "main" layout resource
            SetContentView (Resource.Layout.Main);

            // Get our button from the layout resource,
            // and attach an event to it
            Button button = FindViewById<Button> (Resource.Id.myButton);
            
            button.Click += delegate {
                button.Text = string.Format ("{0} clicks!", count++);
            };

            var result = await this.ocrApi.Init ("eng");
        }
    }
}
`

**Comment by pandrija** [comment]
Thx - works great!
