### ISSUE TITLE
0.3.1 breaks, have to go back to 2.1.0

### ISSUE THREAD

**Issue by reinhardsual** [halkar/Tesseract.Xamarin#28]
Tried to update from 2.1.0 to 0.3.1, the application crash with unhandled exception.
Using the latest Xamarin forms and Xlabs.
Have to goback to 2.1.0.

Cheers,
Reinhard Sua

**Comment by halkar** [comment]
@reinhardsual hm, weird, will check. Is that on Android or iOS?

**Comment by reinhardsual** [comment]
Android 5.1

**Comment by halkar** [comment]
@reinhardsual could you please post your exception's stacktrace here?

**Comment by reinhardsual** [comment]
Ok. Will try again

**Comment by reinhardsual** [comment]
This is the Message I got.
When I tried version 0.2.11 it works okay.
Hope this helps.


[image: Inline image 1]

**Comment by reinhardsual** [comment]
Sorry I should say 0.2.10.
0.2.11 - 0.3.1 generate that Exception.

**Comment by halkar** [comment]
@reinhardsual image is missing. I can't see the exception.

**Comment by reinhardsual** [comment]
It is an Unhandled Exception (On Android 5.1.1):

Java.Lang.OutOfMemoryError:Failed to allocate a 63489036 byte allocation with 16777216 free bytes and 47MB until OOM

I tried on Android Marshmallow, it does not generate exception, BUT _tesseractApi.SetImage(imageBytes) always return False.

Back to 0.2.10 the same exact code just work fine.

**Comment by halkar** [comment]
@reinhardsual thanks!

**Comment by halkar** [comment]
@reinhardsual are you using latest version of tessdata from https://github.com/tesseract-ocr/tessdata ?
