### ISSUE TITLE
AssemblyVersionInfo.cs is missing

### ISSUE THREAD

**Issue by ddurgaprasad** [halkar/Tesseract.Xamarin#29]
Perhaps AssemblyVersionInfo.cs is missing from the repository.Could you please rectify.I getting below errors

_Severity	Code	Description	Project	File	Line	Suppression State
Error		Source file 'C:\tesseract-master\src\Tesseract.Tests.Console\..\AssemblyVersionInfo.cs' could not be found.	Tesseract.Tests.Console	C:\tesseract-master\src\Tesseract.Tests.Console\CSC		
Error		Source file 'C:\tesseract-master\src\Tesseract\..\AssemblyVersionInfo.cs' could not be found.	Tesseract	C:\tesseract-master\src\Tesseract\CSC		
Error		Source file 'C:\tesseract-master\src\Tesseract.Tests\..\AssemblyVersionInfo.cs' could not be found.	Tesseract.Tests	C:\tesseract-master\src\Tesseract.Tests\CSC_

**Comment by ddurgaprasad** [comment]
I think I got it resolved from the suggestion provided at [](https://github.com/charlesw/tesseract/issues/100)

**_"You'll need to run the build.bat script first."_**

**Comment by halkar** [comment]
Are you sure we are talking about my repo? There is no Tesseract.Tests.Console folder in this project.
