### ISSUE TITLE
Error on Init()

### ISSUE THREAD

**Issue by dazinator** [halkar/Tesseract.Xamarin#3]
I'm getting an exception when calling Init()

![image](https://cloud.githubusercontent.com/assets/3176632/8186965/292a7420-1445-11e5-992e-1a07df851dbb.png)

I have included the tessdata folder and set the content type for all the files as per the instructions.
Any ideas?

**Comment by halkar** [comment]
tessdata must be under Assets folder in Android project. Check out my sample project.

**Comment by dazinator** [comment]
Hmm yes.. I have done that. However your sample does work so must be something to do with my project. Cheers.

**Comment by halkar** [comment]
If you could share your project I'd have a look.
