### ISSUE TITLE
TesseractApi not initialized

### ISSUE THREAD

**Issue by rakesh79mca** [halkar/Tesseract.Xamarin#31]
TesseractApi _api = new TesseractApi (this, AssetsDeployment.OncePerInitialization);
_api.Init ("eng");

when i debugging code and check _api intialized value it is returning false

**Comment by hyderlyger** [comment]
try these files 
[tessdata.zip](https://github.com/halkar/Tesseract.Xamarin/files/375666/tessdata.zip)

**Comment by halkar** [comment]
@rakesh79mca you do not await the Init method.
