### ISSUE TITLE
Not getting correct data string in Xamarin.iOS and Xamarin.Android

### ISSUE THREAD

**Issue by Prajakta6** [halkar/Tesseract.Xamarin#35]
I have used Tesseract OCR for scanning the receipts and fetching the data from the receipts. But the output string I get is not even in readable format. 

![img_0885](https://cloud.githubusercontent.com/assets/14888096/22587592/4a607120-ea28-11e6-8083-e7ec88e7b879.JPG)
 
Following is the output string I get:

4
a
£355 5
S" 1
? k ,
4?,“ ,
n5, _ g  '
.~ :' «
I, .
.

Need help to get correct data formatted string.

**Comment by halkar** [comment]
You need to prepare the image first. It should be much more contrast.
