### ISSUE TITLE
using in PCL project

### ISSUE THREAD

**Issue by YordanYanakiev** [halkar/Tesseract.Xamarin#36]
Hello.
I need to use it in PCL based project ( Android specifically ( iOS is not needed atm ) ) ( Forms is not a viable option atm ), but I cant even add it to using clause by some reason unknown disregarding i've installed it.
Is it working in PCL projects at all, and if it does - please post a small sample and description how to make it works.

**Comment by halkar** [comment]
No, this project has portable interface but to make it work you need to initialise it in a platform-specific project.
