### ISSUE TITLE
UWP Xamarin Form sample

### ISSUE THREAD

**Issue by JimSEOW** [halkar/Tesseract.Xamarin#39]
Can this platform be supported?

**Comment by halkar** [comment]
@JimSEOW UWP is not supported. If there is an implementation of Tesseract for UWP I could incorporate it but I can't find any.

**Comment by ysmoradi** [comment]
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/OCR

UWP has built-in support for OCR. Shall we implement Tesserect's interface contract as like as what is done on android/iOS using UWP OCR Engine?
