### ISSUE TITLE
Build and run the project Tesseract.Nuget.Test pop below error. Any idea?

### ISSUE THREAD

**Issue by band888888** [halkar/Tesseract.Xamarin#41]
Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Context)' on type 'TesseractApi'. ---> dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tesseract.nuget.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.tesseract.nuget.test-1/lib/arm64, /system/fake-libs64, /data/app/com.tesseract.nuget.test-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "liblept.so" (See inner exception for details.)

**Comment by halkar** [comment]
@band888888 can you try https://github.com/halkar/Tesseract.Xamarin/tree/feature/updating-native-version ?

**Comment by halkar** [comment]
Merged to `master`. Try latest version.
