### ISSUE TITLE
HOCR support

### ISSUE THREAD

**Issue by TheHippiez** [halkar/Tesseract.Xamarin#44]
Hello,

At this point this project does not support the HOCR function. ( on Android ). Tess Two has implemented this somewhere in the past, is it possible that the package could receive an update? 

Luke

**Comment by halkar** [comment]
If something is implemented in tess-two I can make it work in my project as well but as I'm extremely busy right now I can't tell you when I will be able to add this feature (it will take one or two weeks).

**Comment by TheHippiez** [comment]
Thanks for your response! I'm not sure if I'll be able to fix this issue myself, but if you have no time to do it I will have a look into it. ( I have a C++ background, all this java like stuff is pretty new for me )

**Comment by halkar** [comment]
Fixed in 0.3.4
