### ISSUE TITLE
How to use in Xamarin.Forms include UWP?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [halkar/Tesseract.Xamarin#46]
How to use in Xamarin.Forms include UWP?

**Comment by halkar** [comment]
Same way as on any other platform.

**Comment by halkar** [comment]
Tesseract doesn't support UWP

**Comment by nguyenthanhliemfc** [comment]
Thank you! Do you know any libraries OCR in Xamarin.forms support UWP?

**Comment by halkar** [comment]
I don't know what specific features you need for Xamarin.Forms but for UWP you will find a pretty good OCR engine https://docs.microsoft.com/en-us/uwp/api/windows.media.ocr.ocrengine
