### ISSUE TITLE
Android too Slow OCR

### ISSUE THREAD

**Issue by darkdoctor** [halkar/Tesseract.Xamarin#48]
Hi.

I have successfully implemented the OCR on Android Xamarin.

I have to wait 78 Seconds only to get the result for this image ( https://i.imgur.com/ZYjUEQz.jpg ) and I do not think this is fine. 

The result is fine but the time processing is soo long.

Any suggestion or advice would be much appreciated.

**Comment by halkar** [comment]
https://github.com/tesseract-ocr/tesseract
