### ISSUE TITLE
iOS crash on Init()

### ISSUE THREAD

**Issue by c-lamont** [halkar/Tesseract.Xamarin#54]
I am having trouble with `await _tesseractApi.Init(“eng”);`

I have tried everything but this silently kills the app.

In the Application output there is only one line that may reference the issue: `actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53`

The file is definitely added: `<BundleResource Include="Resources\tessdata\eng.traineddata" />`

**Comment by c-lamont** [comment]
So I think the blog post link to download the files might have changed, or there needs to be more explanation on what files you need to download. I downloaded just the `eng.traineddata` file but turns out you need all of these: https://github.com/halkar/Tesseract.Xamarin/tree/master/Tesseract.Forms.Test/tessdata

**Comment by halkar** [comment]
Yes, you need all `eng.*` files.
